spring:
  application:
    name: training-metrics-api

  datasource:
    url: jdbc:postgresql://localhost:5432/training_metrics
    username: ${DB_USERNAME:training_user}
    password: ${DB_PASSWORD:training_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080