CREATE TABLE athlete (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    birth_date  DATE,
    sport       VARCHAR(255) NOT NULL,
    weight_in_kg DOUBLE PRECISION
);
