CREATE TABLE training_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            DATE NOT NULL,
    sport           VARCHAR(255) NOT NULL,
    rpe             INTEGER NOT NULL CHECK (rpe >= 1 AND rpe <= 10),
    duration_in_min INTEGER NOT NULL CHECK (duration_in_min >= 1),
    target_zone     VARCHAR(2) NOT NULL,
    athlete_id      BIGINT NOT NULL,
                    CONSTRAINT fk_session_athlete FOREIGN KEY (athlete_id) REFERENCES athlete(id)
);
