CREATE TABLE weekly_wellness (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id           BIGINT  NOT NULL,
    week_start_date      DATE    NOT NULL,
    perceived_difficulty INTEGER NOT NULL CHECK (perceived_difficulty >= 1 AND perceived_difficulty <= 5),
    perceived_fatigue    INTEGER NOT NULL CHECK (perceived_fatigue >= 1 AND perceived_fatigue <= 5),
    motivation           INTEGER NOT NULL CHECK (motivation >= 1 AND motivation <= 5),
                         CONSTRAINT fk_wellness_athlete FOREIGN KEY (athlete_id) REFERENCES athlete(id),
                         CONSTRAINT uq_wellness_athlete_week UNIQUE (athlete_id, week_start_date)
);
