CREATE TABLE load_report (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    athlete_id        BIGINT    NOT NULL,
    week_start_date   DATE      NOT NULL,
    total_foster_load INTEGER   NOT NULL,
    session_count     INTEGER   NOT NULL,
    updated_at        TIMESTAMP NOT NULL,
                      CONSTRAINT fk_load_report_athlete FOREIGN KEY (athlete_id) REFERENCES athlete(id),
                      CONSTRAINT uq_load_report_athlete_week UNIQUE (athlete_id, week_start_date)
);
